config/routes.rb
Cvpankki::Application.routes.draw do
  resources :cvs do
    resources :projects
    resources :languages
    resources :educations
  end

  root :to => 'cvs#index'

end

app/models/cv.rb
class Cv < ActiveRecord::Base
  attr_accessible :description, :forename, :freetext, :surname, :title, :skills_attributes

  validates :forename, :presence => :true
  validates :surname, :presence => :true

  has_many :projects, :dependent => :destroy
  has_many :languages, :dependent => :destroy
  has_many :educations, :dependent => :destroy
  has_many :skills

  accepts_nested_attributes_for :skills, :allow_destroy => :true,
        :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :cv
  attr_accessible :description, :enddate, :startdate, :title

  validates :title, :presence => :true
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :cv
  attr_accessible :level, :name

  validates :name, :presence => :true
  validates :level, :presence => :true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :cv
  attr_accessible :customer, :description, :enddate, :startdate, :title

  validates :customer, :presence => :true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :cv
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  # GET /cvs
  # GET /cvs.json
  def index
    @cvs = Cv.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cvs }
    end
  end

  # GET /cvs/1
  # GET /cvs/1.json
  def show
    @cv = Cv.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cv }
    end
  end

  # GET /cvs/new
  # GET /cvs/new.json
  def new
    @cv = Cv.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cv }
    end
  end

  # GET /cvs/1/edit
  def edit
    @cv = Cv.find(params[:id])
  end

  # POST /cvs
  # POST /cvs.json
  def create
    @cv = Cv.new(params[:cv])

    respond_to do |format|
      if @cv.save
        format.html { redirect_to @cv, notice: 'Cv was successfully created.' }
        format.json { render json: @cv, status: :created, location: @cv }
      else
        format.html { render action: "new" }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cvs/1
  # PUT /cvs/1.json
  def update
    @cv = Cv.find(params[:id])

    respond_to do |format|
      if @cv.update_attributes(params[:cv])
        format.html { redirect_to @cv, notice: 'Cv was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.json
  def destroy
    @cv = Cv.find(params[:id])
    @cv.destroy

    respond_to do |format|
      format.html { redirect_to cvs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def create
    @cv = Cv.find(params[:cv_id])
    @education = @cv.educations.create(params[:education])
    redirect_to cv_path(@cv)
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @education = @cv.educations.find(params[:id])
    @education.destroy
    redirect_to cv_path(@cv)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def create
    @cv = Cv.find(params[:cv_id])
    @language = @cv.languages.create(params[:language])
    redirect_to cv_path(@cv)
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @language = @cv.languages.find(params[:id])
    @language.destroy
    redirect_to cv_path(@cv)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def create
    @cv = Cv.find(params[:cv_id])
    @project = @cv.projects.create(params[:project])
    redirect_to cv_path(@cv)
  end

  def destroy
    @cv = Cv.find(params[:cv_id])
    @project = @cv.projects.find(params[:id])
    @project.destroy
    redirect_to cv_path(@cv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
  def join_skills(cv)
    cv.skills.map { |t| t.name }.join(", ")
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cvs/_form.html.erb
<% @cv.skills.build %>
<%= form_for(@cv) do |cv_form| %>
  <% if @cv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cv.errors.count, "error") %> prohibited this cv from being saved:</h2>

      <ul>
      <% @cv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= cv_form.label :forename %><br />
    <%= cv_form.text_field :forename %>
  </div>
  <div class="field">
    <%= cv_form.label :surname %><br />
    <%= cv_form.text_field :surname %>
  </div>
  <div class="field">
    <%= cv_form.label :title %><br />
    <%= cv_form.text_field :title %>
  </div>
  <div class="field">
    <%= cv_form.label :description %><br />
    <%= cv_form.text_area :description %>
  </div>
  <h2>Skills</h2>
  <%= render :partial => 'skills/form',
        :locals => {:form => cv_form} %>
  <div class="field">
    <%= cv_form.label :freetext %><br />
    <%= cv_form.text_area :freetext %>
  </div>
  <div class="actions">
    <%= cv_form.submit %>
  </div>
<% end %>

app/views/cvs/edit.html.erb
<h1>Editing cv</h1>

<%= render 'form' %>

<%= link_to 'Show', @cv %> |
<%= link_to 'Back', cvs_path %>

app/views/cvs/index.html.erb
<h1>Listing cvs</h1>

<table>
  <tr>
    <th>Forename</th>
    <th>Surname</th>
    <th>Title</th>
    <th>Description</th>
    <th>Freetext</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cvs.each do |cv| %>
  <tr>
    <td><%= cv.forename %></td>
    <td><%= cv.surname %></td>
    <td><%= cv.title %></td>
    <td><%= cv.description %></td>
    <td><%= cv.freetext %></td>
    <td><%= link_to 'Show', cv %></td>
    <td><%= link_to 'Edit', edit_cv_path(cv) %></td>
    <td><%= link_to 'Destroy', cv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cv', new_cv_path %>

app/views/cvs/new.html.erb
<h1>New cv</h1>

<%= render 'form' %>

<%= link_to 'Back', cvs_path %>

app/views/cvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Forename:</b>
  <%= @cv.forename %>
</p>

<p>
  <b>Surname:</b>
  <%= @cv.surname %>
</p>

<p>
  <b>Title:</b>
  <%= @cv.title %>
</p>

<p>
  <b>Description:</b>
  <%= @cv.description %>
</p>

<p>
  <b>Skills:</b>
  <%= join_skills(@cv) %>
</p>

<p>
  <b>Freetext:</b>
  <%= @cv.freetext %>
</p>

<h2>Languages</h2>
<%= render @cv.languages %>

<h2>Add a language:</h2>
<%= render "languages/form" %>

<h2>Projects</h2>
<%= render @cv.projects %>

<h2>Add a project:</h2>
<%= render "projects/form" %>

<h2>Educations</h2>
<%= render @cv.educations %>

<h2>Add an education:</h2>
<%= render "educations/form" %>

<%= link_to 'Edit', edit_cv_path(@cv) %> |
<%= link_to 'Back', cvs_path %>

app/views/educations/_education.html.erb
<p><b>Start date:</b>
  <%= education.startdate %></p>

<p><b>End date:</b>
  <%= education.enddate %></p>

<p><b>Title:</b>
  <%= education.title %></p>

<p><b>Description:</b>
  <%= education.description %></p>

<p>
  <%= link_to 'Delete education', [education.cv, education],
                :confirm => 'Are you sure?',
                :method => :delete %>
</p>

app/views/educations/_form.html.erb
<%= form_for([@cv, @cv.educations.build]) do |f| %>
  <div class="field">
    <%= f.label :startdate %>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %>
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/_form.html.erb
<%= form_for([@cv, @cv.languages.build]) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/_language.html.erb
<p><b>Language:</b>
  <%= language.name %></p>

<p><b>Level:</b>
  <%= language.level %></p>

<p>
  <%= link_to 'Delete language', [language.cv, language],
                :confirm => 'Are you sure?',
                :method => :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cvpankki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for([@cv, @cv.projects.build]) do |f| %>
  <div class="field">
    <%= f.label :startdate %>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %>
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<p><b>Start date:</b>
  <%= project.startdate %></p>

<p><b>End date:</b>
  <%= project.enddate %></p>

<p><b>Customer:</b>
  <%= project.customer %></p>

<p><b>Title:</b>
  <%= project.title %></p>

<p><b>Description:</b>
  <%= project.description %></p>

<p>
  <%= link_to 'Delete project', [project.cv, project],
                :confirm => 'Are you sure?',
                :method => :delete %>
</p>

app/views/skills/_form.html.erb
<%= form.fields_for :skills do |skill_form| %>
  <div class="field">
    <%= skill_form.label :name, 'Skill:' %>
    <%= skill_form.text_field :name %>
  </div>
  <% unless skill_form.object.nil? || skill_form.object.new_record? %>
    <div class="field">
      <%= skill_form.label :_destroy, 'Remove:' %>
      <%= skill_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>